name: 'Setup Maven & GraalVM Environment'
description: 'Sets up GraalVM JDK 25.0.2, generates Maven settings.xml, and exports MAVEN_ARGS'

runs:
  using: 'composite'
  steps:
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '25.0.2'
        distribution: 'graalvm'
        github-token: ${{ env.GITHUB_TOKEN }}
        cache: maven

    - name: Generate Maven settings.xml
      uses: s4u/maven-settings-action@v4.0.0
      with:
        servers: |
          [
            {
              "id": "github",
              "username": "${{ env.GH_USER }}",
              "password": "${{ env.GH_TOKEN }}"
            }
          ]
        repositories: |
          [
            {
              "id": "github",
              "name": "Mogul Github Artifacts",
              "url": "https://maven.pkg.github.com/bootiful-media-mogul/artifacts"
            }
          ]